### PR TITLE
Simplify build and test process

### PR DESCRIPTION
**Pull request by fw-brice**
The patch is no longer needed, so delete that. A Dockerfile for building
and testing is maintained in the v8-riscv-ci repo. For testing, we will
now use `gm` to run the standard tests, so the script is no longer
needed:
```
gm riscv64.debug.checkall --progress=verbose
```

### CODE REVIEW

**Comment by lazyparser** [comment]
seems that the CI is not happy :)

**Comment by lazyparser** [comment]
the build.patch is applied for a different repo. I think we should submit a patch to the chromium/build repo, Had we submit yet?

besides, I've noticed there is a out of patch modification in my personal script:

```
sed -i 's,riscv64-linux-gnu,riscv64-unknown-linux-gnu,' \
    $V8_ROOT/v8/build/toolchain/linux/BUILD.gn

```
https://github.com/isrc-cas/PLCT-Toolbox/blob/master/init_v8_all_in_one.sh#L106

Is this still relevant?

**Comment by fw-brice** [comment]
The CI seems correct; there are just 2 known failures right now. One is a timing issue, which maybe we should skip, and one is related tp #349.

I don't think we need any patches anymore. Let me know the details of any issues that you see.

**Review by lazyparser — APPROVED** [review]
LGTM

**Pull request merged**
