### PR TITLE
Fix #344: assembler-riscv64.cc:2457:15: warning: variable 'part' set but not used [-Wunused-but-set-variable]

### LINKED ISSUE #344: assembler-riscv64.cc:2457:15: warning: variable 'part' set but not used [-Wunused-but-set-variable]
Seems an easy issue but should be fixed before upstreaming.

```
Done. Made 219 targets from 95 files in 139ms
ninja: Entering directory `out/riscv64.native.debug'                                                                                                                                                        [3041/4701] CXX obj/v8_base_without_compiler/assembler-riscv64.o                                                                                                                                            ../../src/codegen/riscv64/assembler-riscv64.cc: In static member function 'static int v8::internal::Assembler::li_estimate(int64_t, bool)':
../../src/codegen/riscv64/assembler-riscv64.cc:2457:15: warning: variable 'part' set but not used [-Wunused-but-set-variable]
 2457 |       int32_t part;                                                                                                                                                                                       |               ^~~~
```

### PR DESCRIPTION
**Pull request by Nekhlyudov**
the previous pr was closed by mistake.

### CODE REVIEW

**Comment by qjivy** [comment]
Perhaps it's better to add "Fix #344"  to the commit log.

**Comment by fw-brice** [comment]
Thanks for the improvement @Nekhlyudov! Have you signed the [CLA](https://v8.dev/docs/contribute)? If not, please do so. Also, please add another commit to this branch in which you add your name/email to the AUTHORS file. We have to ensure both of these are complete in order to get changes upstreamed.

**Review by fw-brice — APPROVED** [review]
LGTM

**Review by fw-brice — APPROVED** [review]

**Review by fw-brice — CHANGES_REQUESTED** [review]
Bringing this back to your attention: @Nekhlyudov 

> Have you signed the CLA? If not, please do so. Also, please add another commit to this branch in which you add your name/email to the AUTHORS file. We have to ensure both of these are complete in order to get changes upstreamed.

**Pull request closed without merging**
