### PR TITLE
implement deserialization_set_target_internal_reference_at

### PR DESCRIPTION
**Pull request by thomasyonug**
impl issue #55

### CODE REVIEW

**Comment by fw-brice** [comment]
Can the test be unskipped with this change? (`test/mjsunut/mjsunit.status`):
```
  'wasm/compiled-module-serialization': [SKIP], # issue 55
```

If so, please add that to this commit. Also, please add "Fixes #55" to the commit message.

**Comment by thomasyonug** [comment]
> Can the test be unskipped with this change? (`test/mjsunut/mjsunit.status`):
> 
> ```
>   'wasm/compiled-module-serialization': [SKIP], # issue 55
> ```
> 
> If so, please add that to this commit. Also, please add "Fixes #55" to the commit message.

Yeah, it's pass. Could I just delete this line in mjsunit.status or change SKIP to PASS ?

**Comment by penguinwu** [comment]
Yes, you can delete the line in status file (which will enable the test).

**Comment by fw-brice** [comment]
Please squash your two commits into one with the message:
```
Implement deserialization_set_target_internal_reference_at

Fixes #55
```

**Comment by thomasyonug** [comment]
Ok, done. :)

**Pull request merged**
