### PR TITLE
Add support for cross compiling to riscv64

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I've yet to figure out all the internal binary tools so I can't build natively, but with this I can at least get a cross compiled version up and running.  Simple stuff seems to work (console.log("hello, world"); 1.1) but I've yet to get the cross test suite running.  I'm using GCC for the build, as that seems to be the default for most systems and our LLVM port is a bit on the new side.

### CODE REVIEW

**Comment by luyahan** [comment]
in #23  I run the cctest case.

**Comment by palmer-dabbelt** [comment]
@luyahan awesome!  I was about to go to bed...  Do you mind running it with #26?  It's probably not going to fix any bugs, but without that any native test runs would be very suspect.

I'll take a look tomorrow morning.

**Comment by luyahan** [comment]
> @luyahan awesome! I was about to go to bed... Do you mind running it with #26? It's probably not going to fix any bugs, but without that any native test runs would be very suspect.
> 
> I'll take a look tomorrow morning.

I'll try it.I have an question about toolchain. I build a riscv64-toolchain from ttps://github.com/riscv/riscv-gnu-toolchain.After building it, the gcc prefix name is `riscv64-unknown-linux-gnu-`, but your gcc toolchain prefix name is `riscv64-linux-gnu-`.To unify the riscv toolchain, I want to know the source of your toolchain

**Comment by lazyparser** [comment]
> > @luyahan awesome! I was about to go to bed... Do you mind running it with #26? It's probably not going to fix any bugs, but without that any native test runs would be very suspect.
> > I'll take a look tomorrow morning.
> 
> I'll try it.I have an question about toolchain. I build a riscv64-toolchain from https://github.com/riscv/riscv-gnu-toolchain. After building it, the gcc prefix name is `riscv64-unknown-linux-gnu-`, but your gcc toolchain prefix name is `riscv64-linux-gnu-`.To unify the riscv toolchain, I want to know the source of your toolchain

Hi @palmer-dabbelt 

FYI the PLCT lab (includes luyahan and me) uses this script for standard toolchain building:

https://github.com/isrc-cas/PLCT-Toolbox/blob/master/build_riscv_toolchain.sh

**Comment by palmer-dabbelt** [comment]
@luyahan my toolchain comes from the Debian packages.  That's the naming scheme the arm64 port was using, so I just copied it.

**Pull request merged**
